# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'verbose_name': '\u7528\u6237\u7ec4', 'verbose_name_plural': '\u7528\u6237\u7ec4'},
        ),
    ]
