# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(to='web.UserGroup'),
        ),
    ]
