# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('web', '0004_auto_20160409_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chatgroup',
            field=models.ManyToManyField(blank=True, default=None, to='chat.ChatGroup'),
        ),
    ]
