# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_userprofile_chatgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friend',
            field=models.ManyToManyField(related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
